version: '3.9'

services:
  wallet-app:
    build: ./
    command: ./wait-for-postgres.sh db ./wallet-app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
    
  db:
    restart: always
    image: postgres:17.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

    volumes:
      - db-data:/var/lib/postgresql/data


  migrate:
    image: migrate/migrate
    entrypoint: [
      "migrate",
      "-path", "./migration",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migration:/migration
    depends_on:
      - db
    restart: on-failure

volumes:
  db-data: